spring:
  first-datasource:
    skip: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    table: flyway-schema-history
    location: db/migration/clouddb01
  second-datasource:
    skip: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    table: flyway-schema-history
    location: db/migration/clouddb02
